### ISSUE TITLE
Support for mouse drivers

### ISSUE THREAD

**Issue by edualm** [FruityRazer/FruityKit#6]
Implement support for mouse drivers.

Fixes #3 and #5.

**Comment by edualm** [comment]
Beta support in https://github.com/FruityRazer/FruityUI/releases/tag/v1.2b1.

**Comment by alexfry** [comment]
Hey..

I tried the build posted here:
https://github.com/FruityRazer/FruityUI/releases/tag/v1.2b1

It's recognising the device, and displaying the appropriate UI, but no changes are occurring on the actual device when hitting Save.

![image](https://user-images.githubusercontent.com/900885/84608613-90a2d600-aef6-11ea-9ffe-2a8473cfc533.png)

If it's any help, the most recent build of Razer-MacOS now has basic working support for the Razer mice (tested with the same mouse I'm using here).
https://github.com/1kc/razer-macos/

**Comment by edualm** [comment]
You're right @alexfry - there is something wrong. Starlight shouldn't be appearing, but the other effects should be working nonetheless.

Anyway - I now have a mouse I can use to test. I will work on that as soon as I'm able to today.

Thanks for that repo - it can be useful in helping me debug the root cause.

**Comment by edualm** [comment]
Hey @alexfry,

Mind trying this new build? https://github.com/FruityRazer/FruityUI/releases/tag/v1.2b2

Works with a Razer Basilisk, so it should (hopefully!) work with your device too.

Thanks!

**Comment by alexfry** [comment]
That's working! (partially at least).

Mouse is now recognised, and accepts changes.

Issues:
• Changes only properly effects the scroll wheel.
• Logo goes into breathing mode, and seems to get the colour from the scroll wheel, but only on boot, each subsequent change does not effect logo.
• No control over the side LED strips.
• Colour selector is a hue wheel only, with no saturation control.

**Comment by edualm** [comment]
Hey @alexfry,

Glad to hear that. Here is a new build: https://github.com/FruityRazer/FruityUI/releases/tag/v1.2b5

It is untested on your specific mouse as I don't own it, but:

- [X] Changes only properly effects the scroll wheel. - **This should now be fixed.**
- [X] Logo goes into breathing mode, and seems to get the colour from the scroll wheel, but only on boot, each subsequent change does not effect logo. - **Not sure why this might be, but hopefully my changes fixed this too.**
- [X] No control over the side LED strips. - **This should now respect the selected effect.**
- [ ] Colour selector is a hue wheel only, with no saturation control. - **What would you like to be changed? I don't fully understand your request, sorry.**

**Comment by alexfry** [comment]
Hey, that's now setting all LED groups correctly!
Awesome!!

What I mean by Hue wheel is that you can pick colours, but only from a set of 100% saturated values. If you had a colour selector that had saturation and brightness as well, all colours can be selected. Like the example below.
![image](https://user-images.githubusercontent.com/900885/84761258-8bd04600-b00c-11ea-9776-2d4178f5f140.png)

The colour selector in Synapse 3 under Windows works this way. As far as I know all values are sent as RGB values.

Rather than only being able to send 100% HOT PINK, you can also send a very dim but saturated pink, or a bright but almost white desaturated pink.

It would also be great to be able to set the colour of the individual LED zones rather than the entire thing.

I know this leads to a lot of extra UI work (As the Lancehead has something like 18 different LED zones). I wonder if it's possible to export the lighting profile out of Synapse 3 into a file somehow, and just set it on the Mac side?

**Comment by edualm** [comment]
Glad that it works! :D

Regarding the color picker... I know the current one isn't perfect. That's something to think about and change. Probably the next feature to implement!

As for the individual zones, I don't think Synapse allows you to export a profile, but I could look into that. As for actually implementing that... It's possible, one idea would be to make FruityUI accept a JSON file of sorts with zones, just like I do for devices where I implemented software-based effects (I am currently using, right now, different illumination zones for my keyboard)... but even if I could just accept that JSON file, it'd still be a lot of extra work. I can probably work on that, sounds like a good idea, but I don't know when I'll be able to get to it.

I'm going to close this issue and make 1.2 a final release, but I'm opening two issues for your requests:

https://github.com/FruityRazer/FruityUI/issues/13
https://github.com/FruityRazer/FruityKit/issues/10
